#端口号配置
server:
  port: 8089
#数据库连接配置
spring:
  main:
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.160.51:3306/practice?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: BJTUSoftware2025
  mail:
    host: smtp.163.com
    port: 465
    username: 18201500146@163.com
    password: NNUXwFAbnDVdgYnC
    default-encoding: UTF-8
    properties:
      "mail.smtp.auth": true
      "mail.smtp.ssl.enable": true


web:
  uploadpath: uploads/
  load-path: file:uploads/


jwt:

  issuer: itmk

  secret: com.itmk

  expiration: 3000


# 白名单URL配置
ignore:
  url: /api/sysUser/login,/api/sysUser/getImage,/api/upload/uploadImage,/wxapi/allApi,/swagger-ui/**,/swagger-ui.html,/swagger-resources/**,/v3/api-docs,/v2/api-docs,/webjars/**,/api/sysUser/api-docs,/webjars,/doc.html,/favicon.ico



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:

      update-strategy: not_empty

logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'


geetest:
  id: 46cd832af3cf1316d9503376f18d8d69
  key: c7d8e60ca8d7e82f021e9da3a59ddb62
  api:
    url: http://api.geetest.com/v4/validate
  enabled: false